"""Mask ImageGen additions, preserve prior layers, and enforce the family palette.

Art is generated by image_gen. This script only extracts layers, composites,
performs the explicitly required color sweep, and makes review artifacts.
"""
from pathlib import Path
import argparse
import hashlib
import json
import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parent
COLORS = json.loads((ROOT / 'palette.json').read_text(encoding='utf-8'))['colors']
PAL = np.array([tuple(bytes.fromhex(c['hex'][1:])) for c in COLORS], dtype=np.int32)
STAGES = ['tier-1', 'tier-2', 'tier-3', 'tier-4-curse', 'tier-4-empowerment']


def sweep(im, allowed=range(12)):
    """Nearest exact RGB assignment; never change geometry or alpha."""
    arr = np.array(im.convert('RGBA'))
    before = arr[:, :, 3].copy()
    palette = PAL[list(allowed)]
    for y in range(0, arr.shape[0], 64):
        rgb = arr[y:y+64, :, :3].astype(np.int32)
        distances = ((rgb[:, :, None, :] - palette[None, None, :, :]) ** 2).sum(axis=3)
        arr[y:y+64, :, :3] = palette[distances.argmin(axis=2)]
    arr[before == 0, :3] = 0
    assert np.array_equal(before, arr[:, :, 3])
    return Image.fromarray(arr)


def clean_cutout(im):
    """Extract visible artwork, discarding isolated nearly invisible alpha specks.

    Preserve generated alpha around real edges. This precedes palette conversion.
    """
    arr = np.array(im.convert('RGBA'))
    support = Image.fromarray(np.uint8(arr[:, :, 3] >= 16) * 255).filter(ImageFilter.MaxFilter(5))
    arr[np.array(support) == 0] = 0
    return Image.fromarray(arr)


def prepare(source):
    raw = Image.open(source).convert('RGBA')
    (ROOT / 'sources').mkdir(exist_ok=True)
    raw.save(ROOT / 'sources/tier-1.png')
    base = sweep(clean_cutout(raw))
    base.save(ROOT / 'tier-1.png')
    print(json.dumps({'size': base.size, 'bounds': base.getbbox()}))


def add_layer(stage, parent, source, boxes):
    prior = Image.open(ROOT / f'{parent}.png').convert('RGBA')
    raw = Image.open(source).convert('RGBA')
    if raw.size != prior.size:
        raise ValueError(f'Canvas mismatch: generated {raw.size}, parent {prior.size}')
    raw.save(ROOT / 'sources' / f'{stage}.png')
    mask = Image.new('L', prior.size)
    draw = ImageDraw.Draw(mask)
    for box in boxes:
        draw.rectangle(box, fill=255)
    # Mask new features only. All prior nontransparent pixels remain immutable.
    a = np.array(clean_cutout(raw))
    p = np.array(prior)
    keep = (np.array(mask) != 0) & (p[:, :, 3] == 0)
    a[~keep] = 0
    allowed = list(range(12))
    if stage == 'tier-4-curse':
        allowed += [14, 15]
    if stage == 'tier-4-empowerment':
        allowed += [12, 13]
    layer = sweep(Image.fromarray(a), allowed)
    (ROOT / 'layers').mkdir(exist_ok=True)
    layer.save(ROOT / 'layers' / f'{stage}.png')
    mask.save(ROOT / 'layers' / f'{stage}-selection.png')
    out = sweep(Image.alpha_composite(prior, layer), allowed)
    out.save(ROOT / f'{stage}.png')
    assert np.array_equal(np.array(out)[p[:, :, 3] > 0], p[p[:, :, 3] > 0])
    print(json.dumps({'stage': stage, 'bounds': out.getbbox(), 'added_pixels': int(np.count_nonzero(np.array(layer)[:, :, 3]))}))


def finish():
    base = np.array(Image.open(ROOT / 'tier-1.png').convert('RGBA'))
    locked = base[:, :, 3] > 0
    report = {'canvas': [base.shape[1], base.shape[0]], 'core_axis_x': 627,
              'ground_anchor': [627, 1156], 'roof_peak': [627, 459],
              'palette_rgb': PAL.tolist(), 'images': []}
    images = []
    parents = {'tier-2': 'tier-1', 'tier-3': 'tier-2', 'tier-4-curse': 'tier-3', 'tier-4-empowerment': 'tier-3'}
    for stage in STAGES:
        path = ROOT / f'{stage}.png'
        im = Image.open(path).convert('RGBA')
        before = np.array(im)
        allowed = list(range(12)) + ([14, 15] if stage == 'tier-4-curse' else [12, 13] if stage == 'tier-4-empowerment' else [])
        final = sweep(im, allowed)
        final.save(path)
        arr = np.array(Image.open(path).convert('RGBA'))
        assert np.array_equal(before[:, :, 3], arr[:, :, 3]), 'Sweep changed alpha'
        assert np.array_equal(arr[locked], base[locked]), 'Base pixel changed'
        assert arr.shape == base.shape
        used = np.unique(arr[arr[:, :, 3] > 0, :3], axis=0)
        assert all(tuple(c) in {tuple(p) for p in PAL[allowed]} for c in used)
        if stage in parents:
            prev = np.array(Image.open(ROOT / f'{parents[stage]}.png').convert('RGBA'))
            assert np.array_equal(arr[prev[:, :, 3] > 0], prev[prev[:, :, 3] > 0]), 'Prior upgrade changed'
        visible_y, visible_x = np.where(arr[:, :, 3] > 127)
        assert int(visible_y.max()) == 1156, 'Ground moved'
        report['images'].append({'file': path.name, 'palette_colors_used': len(used),
            'sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
            'locked_base_pixels_identical': True, 'prior_layers_identical': True,
            'core_offset_xy': [0, 0], 'ground_anchor_xy': [627, 1156],
            'visible_bounds': [int(visible_x.min()), int(visible_y.min()), int(visible_x.max()), int(visible_y.max())],
            'palette_sweep_preserved_alpha': True})
        images.append(final)
    (ROOT / 'validation.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    font_path = 'C:/Windows/Fonts/georgia.ttf'
    title_font = ImageFont.truetype(font_path, 36)
    label_font = ImageFont.truetype(font_path, 22)
    small_font = ImageFont.truetype(font_path, 17)
    board = Image.new('RGB', (1800, 820), '#202821')
    d = ImageDraw.Draw(board)
    d.text((900, 40), 'HEX LANTERN', fill='#C6B8C3', font=title_font, anchor='mt')
    d.text((900, 90), 'The Witchlight Shrine', fill='#968F76', font=label_font, anchor='mt')
    labels = ['Tier 1', 'Tier 2', 'Tier 3', 'Tier 4 - Curse', 'Tier 4 - Empowerment']
    for i, (im, label) in enumerate(zip(images, labels)):
        thumb = im.resize((350, 350), Image.Resampling.NEAREST)
        board.paste(thumb, (5+i*360, 170), thumb)
        d.text((180+i*360, 540), label, fill='#C6B8C3', font=label_font, anchor='mt')
        small = im.resize((144, 144), Image.Resampling.NEAREST)
        board.paste(small, (108+i*360, 580), small)
    d.text((900, 750), 'Shared base preserved pixel for pixel  |  One 16-color family palette', fill='#968F76', font=small_font, anchor='mt')
    board.save(ROOT / 'family-review.png')
    frames=[]
    for im in images:
        frame=Image.new('RGB', im.size, '#202821')
        frame.paste(im, (0,0), im)
        frames.append(frame)
    frames[0].save(ROOT / 'alignment-preview.webp', save_all=True, append_images=frames[1:], duration=800, loop=0, lossless=True)
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('mode', choices=['prepare', 'layer', 'finish'])
    parser.add_argument('--source')
    parser.add_argument('--stage')
    parser.add_argument('--parent')
    parser.add_argument('--boxes', help='JSON list of [left,top,right,bottom] masks')
    args = parser.parse_args()
    if args.mode == 'prepare':
        prepare(args.source)
    elif args.mode == 'layer':
        add_layer(args.stage, args.parent, args.source, json.loads(args.boxes))
    else:
        finish()
