extends "res://tests/test_runner.gd"

func run() -> void:
	var slots := VigilSaveSlots.new()
	slots.base_path = "user://mode-tests-" + str(Time.get_ticks_usec())
	var creative := slots.create(0, "creative")
	check(creative != null and creative.is_creative(), "Create Creative in first slot")
	check(creative.add_developer_gold(), "Creative grants gold")
	check(creative.expand("-1,0"), "Creative build has territory")
	var tower := creative.economy.build("rapid", "0,0", 0)
	check(tower != "", "Creative build has tower")
	check(creative.set_balance_stat("enemies", "basic", "hp", 200.0), "Creative tuning")
	var code := slots.export_build(creative, "Hard night", "Basic enemies have 200 HP.")
	check(not code.is_empty(), "Named build exports")
	var survival := slots.create(1, "survival", code)
	check(survival != null and not survival.is_creative(), "Import as Survival")
	check(survival.data.setup.name == "Hard night" and survival.data.setup.description == "Basic enemies have 200 HP.", "Metadata round trip")
	check(survival.data.towers.has(tower) and survival.data.regions.size() == 2 and survival.tuning == creative.tuning, "Layout and custom rules retained")
	var before := survival.data.duplicate(true)
	check(not survival.add_developer_gold() and not survival.set_balance_stat("enemies", "basic", "hp", 300.0) and not survival.set_tower_tier_stat("rapid", "damage", 200.0) and not survival.reset_developer_balance(), "Survival guards all developer mutations")
	check(survival.data == before, "Blocked controls preserve state")
	var imported := slots.create(2, "creative", code)
	check(imported != null and imported.is_creative() and imported.set_balance_stat("enemies", "basic", "hp", 300.0), "Imported Creative remains editable")
	check(slots.create(3, "survival") == null and slots.create(1, "creative") == null, "Exactly three slots, occupied saves protected")
	check(slots.decode_build(code.replace("Hard night", "tampered")).is_empty(), "Damaged export rejected")
	check(survival.reset_progress() and not survival.is_creative() and survival.tuning == creative.tuning, "Survival reset preserves mode and rules")
	var loaded := VigilState.new()
	loaded.save_path = slots.path_for(2)
	check(loaded.load_save() and loaded.is_creative(), "Mode persists on reload")
	var legacy := creative.snapshot()
	legacy.erase("mode")
	check(slots.storage.write(slots.path_for(0), legacy), "Legacy schema accepted")
	loaded.save_path = slots.path_for(0)
	check(loaded.load_save() and loaded.is_creative(), "Existing saves keep Creative controls")
	check(slots.archive(2) and not slots.occupied(2), "Archiving frees a slot without overwriting another save")
	check(slots.create(2, "survival") != null, "Freed slot can select a new mode")
	for slot in range(3):
		clean_test_save(slots.path_for(slot))
	print("Save modes: ", checks, " checks; ", failures.size(), " failures")
	quit(0 if failures.is_empty() else 1)
