extends "res://tests/test_runner.gd"
const TouchScroll = preload("res://scripts/ui/shared/touch_scroll.gd")

func run() -> void:
	var scroll := ScrollContainer.new()
	root.add_child(scroll)
	TouchScroll.attach(scroll)
	var layout := VBoxContainer.new()
	scroll.add_child(layout)
	var first := Button.new()
	layout.add_child(first)
	check(first.mouse_filter == Control.MOUSE_FILTER_PASS, "Buttons inside scroll allow gestures")
	layout.reparent(root, false)
	check(first.mouse_filter == Control.MOUSE_FILTER_STOP, "Reparenting restores original button input boundary")
	var second := Button.new()
	layout.add_child(second)
	check(second.mouse_filter == Control.MOUSE_FILTER_STOP, "Stale scroll observer cannot change new battlefield controls")
	layout.reparent(scroll, false)
	check(first.mouse_filter == Control.MOUSE_FILTER_PASS and second.mouse_filter == Control.MOUSE_FILTER_PASS, "Returning to scroll prepares controls again")
	var nested := ScrollContainer.new()
	layout.add_child(nested)
	var nested_button := Button.new()
	nested.add_child(nested_button)
	check(nested_button.mouse_filter == Control.MOUSE_FILTER_STOP, "Nested scroll retains its own gesture boundary")
	var picker := OptionButton.new()
	var original_action := picker.action_mode
	var original_fit := picker.fit_to_longest_item
	layout.add_child(picker)
	check(picker.action_mode == BaseButton.ACTION_MODE_BUTTON_RELEASE and not picker.fit_to_longest_item, "Dropdown allows a swipe to finish before opening")
	layout.reparent(root, false)
	check(picker.action_mode == original_action and picker.fit_to_longest_item == original_fit, "Dropdown input and sizing restored outside scroll owner")
	layout.reparent(scroll, false)
	check(picker.action_mode == BaseButton.ACTION_MODE_BUTTON_RELEASE, "Dropdown can reattach without stale popup callbacks")
	scroll.queue_free()
	await process_frame
	print("TOUCH SCROLL SCOPE: %d checks, %d failures" % [checks, failures.size()])
	quit(0 if failures.is_empty() else 1)
