"""Rebuild comparison tables directly from preserved measurement JSON."""
import json
from pathlib import Path
from statistics import median

from performance_compare import RESULTS


def read(name):
    return json.loads((RESULTS / (name + '.json')).read_text(encoding='utf-8'))


def summary(rows, key):
    return [median(r[key][metric] for r in rows) for metric in ['mean', 'p95', 'p99']] + [max(r[key]['max'] for r in rows)]


def numbers(values):
    return ' | '.join(f'{value:.2f}' for value in values)


def main():
    out = ['# Measured performance tables', '',
           'Generated by `tools/summarize_performance_changes.py`. Times are milliseconds. '
           'Mean, p95 and p99 columns are medians of the repeated runs; worst is the largest single sample across those runs. '
           'Do not add CPU and GPU timings to frame time: their work overlaps.', '',
           '## Frozen rendering, 390 x 844', '',
           '| Mode | Revision | Mean | p95 | p99 | Worst | Draw calls | Render CPU | Render GPU | Static memory MiB |',
           '|---|---|---:|---:|---:|---:|---:|---:|---:|---:|']
    for mode in ['infinite', 'campaign']:
        for name in ['before', 'after', 'artwork']:
            rows = read(name + ('_render_overview' if name == 'artwork' else '_render'))['rows']
            rows = [r for r in rows if r['case'] == mode and r['viewport'] == [390,844] and r['camera'] == 'overview' and r['variant'] == 'full']
            values = summary(rows, 'frame_ms') + [median(r[k]['mean'] for r in rows) for k in ['draw_calls', 'renderer_cpu_ms', 'renderer_gpu_ms']]
            values += [median(r['static_memory_bytes'] for r in rows)/1048576]
            out.append(f'| {mode} | {name} | {numbers(values)} |')
    out += ['', '## Expanded Infinite simulation', '', '| Fixture | Revision | Mean | p95 | p99 | Worst | Static memory MiB |', '|---|---|---:|---:|---:|---:|---:|']
    before = read('before_simulation')['rows']
    matches = {}
    for name in ['before', 'route', 'configuration', 'after']:
        rows = read(name + '_simulation')['rows']
        matches[name] = all(a['checksum'] == b['checksum'] and a['after'] == b['after'] for a,b in zip(before, rows, strict=True))
        for case in dict.fromkeys(r['case'] for r in rows):
            subset = [r for r in rows if r['case'] == case]
            values = summary(subset, 'tick_ms') + [median(r['static_memory_bytes'] for r in subset)/1048576]
            out.append(f'| {case} | {name} | {numbers(values)} |')
    out += ['', 'All 18 deterministic simulation outcomes match the baseline: `' + str(matches) + '`.', '',
            '## Live application, 390 x 844', '',
            '| Mode | Speed | Revision | FPS | Mean | p95 | p99 | Worst | Simulated / real seconds |',
            '|---|---|---|---:|---:|---:|---:|---:|---:|']
    for mode in ['infinite', 'campaign']:
        for speed in [1,2,4]:
            for name in ['before','after']:
                rows = [r for r in read(f'{name}_live_{speed}x')['rows'] if r['mode'] == mode]
                values = [median(r['actual_fps'] for r in rows)] + summary(rows, 'frame_ms')
                ratio = f"{median(r['simulation_seconds'] for r in rows):.2f} / {median(r['elapsed_seconds'] for r in rows):.2f}"
                out.append(f'| {mode} | {speed}x | {name} | {numbers(values)} | {ratio} |')
    out += ['', '## Sustained desktop 4x, one minute', '', '| Revision | FPS | Mean | p95 | p99 | Worst | Sim / real seconds | Memory start / end MiB |', '|---|---:|---:|---:|---:|---:|---:|---:|']
    for name in ['before','after']:
        r = read(name + '_live_sustained_4x')['rows'][0]
        out.append(f"| {name} | {numbers([r['actual_fps']] + summary([r], 'frame_ms'))} | {r['simulation_seconds']:.2f} / {r['elapsed_seconds']:.2f} | {r['memory_before']/1048576:.2f} / {r['memory_after']/1048576:.2f} |")
    out += ['', '## HUD formatting cost', '', '| Mode | Values change | Revision | Mean | p95 | p99 | Worst |', '|---|---|---|---:|---:|---:|---:|']
    for mode in ['infinite','campaign']:
        for changing in [False,True]:
            for name in ['before','interface','after']:
                rows = [r for r in read(name + '_hud_costs')['rows'] if r['mode']==mode and r['changing']==changing]
                out.append(f'| {mode} | {changing} | {name} | ' + ' | '.join(f'{v:.4f}' for v in summary(rows,'refresh_ms')) + ' |')
    old, new = read('before_campaign_all_waves')['rows'], read('after_campaign_all_waves')['rows']
    campaign_match = all(all(a[k] == b[k] for k in ['counts','health','phase','ticks','waves_completed']) for a,b in zip(old,new,strict=True))
    out += ['', f"Campaign coverage: {len(new)} levels, {sum(r['waves_completed'] for r in new)} waves. Counts, health, phase and tick counts match: **{campaign_match}**. Both runs use the documented survival guard; this is coverage, not a balance win-rate claim."]
    out += ['', '## Campaign simulation across all 144 waves', '', '| Revision | Steps | Weighted mean step ms | Worst step ms | Outcomes match |', '|---|---:|---:|---:|---|']
    for name in ['before', 'route', 'configuration', 'after']:
        if not (RESULTS / (name + '_campaign_all_waves.json')).exists(): continue
        rows = read(name + '_campaign_all_waves')['rows']
        same = all(all(a[k] == b[k] for k in ['counts','health','phase','ticks','waves_completed']) for a,b in zip(old,rows,strict=True))
        steps = sum(r['ticks'] for r in rows)
        weighted = sum(r['tick_ms']['mean'] * r['ticks'] for r in rows) / steps
        out.append(f'| {name} | {steps} | {weighted:.4f} | {max(r["tick_ms"]["max"] for r in rows):.3f} | {same} |')
        matches['campaign_' + name] = same
    if (RESULTS/'android_after.json').exists() and read('android_after').get('complete'):
        out += ['', '## Physical Android, native 1440 x 2304 surface', '', '| Revision | Workload | FPS | Mean | p95 | p99 | Worst | Sim / real seconds |', '|---|---|---:|---:|---:|---:|---:|---:|']
        for name in ['before','after']:
            device = read('android_' + name)
            for mode in ['infinite','campaign']:
                rows = [r for r in device['reports']['render']['rows'] if r['case']==mode]
                out.append(f'| {name} | {mode} frozen | {1000/median(r["frame_ms"]["mean"] for r in rows):.2f} | {numbers(summary(rows,"frame_ms"))} | frozen |')
            for suite in ['live_1','live_2','live_4','sustained_4x']:
                for r in device['reports'][suite]['rows']:
                    out.append(f'| {name} | {r["mode"]} {suite} | {numbers([r["actual_fps"]]+summary([r],"frame_ms"))} | {r["simulation_seconds"]:.2f} / {r["elapsed_seconds"]:.2f} |')
        a, b = read('android_before')['reports']['behavior'], read('android_after')['reports']['behavior']
        matches['android'] = all(x.get('checkpoints',x.get('checksum')) == y.get('checkpoints',y.get('checksum')) for x,y in zip(a['rows'],b['rows'],strict=True)) and not a['failures'] and not b['failures']
        out += ['', f'Android camera and save-restoration digests match across both release exports: **{matches["android"]}**.']
    (RESULTS/'comparison_tables.md').write_text('\n'.join(out)+'\n', encoding='utf-8')
    (RESULTS/'outcome_comparison.json').write_text(json.dumps({'simulation': matches, 'campaign': campaign_match}, indent=2))
    if not all(matches.values()) or not campaign_match: raise SystemExit('Outcome mismatch')
    print('Comparison tables written; outcomes match.', flush=True)


if __name__ == '__main__': main()
